services:
  - type: web
    name: sistem-enedes
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: enedesifb
          property: connectionString
