services:
  - type: web
    name: sistem-enedes
    env: native
    plan: free
    buildCommand: echo "PHP nativo - sem build necessário"
    startCommand: echo "Usando servidor PHP nativo do Render"
    envVars:
      - key: PHP_VERSION
        value: "8.1"
