services:
  - type: web
    name: enedessystem
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: enedes-db
          property: connectionString

databases:
  - name: enedes-db
    databaseName: enedes
    user: enedes_user
    plan: free

